require_relative 'confs/config'

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME

  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY_SIZE
    v.cpus = CPU_COUNT
  end

  config.vm.define MASTER_HOSTNAME do |master|
    master.vm.hostname = MASTER_HOSTNAME
    master.vm.network :private_network, ip: MASTER_IP, device: "eth1"
    master.vm.synced_folder ".", "/vagrant"
    master.vm.provision "shell", privileged: true, path: "scripts/master.sh",
    env: {
      "MASTER_IP" => MASTER_IP
    }
  end

  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network :private_network, ip: WORKER_IP, device: "eth1"
    worker.vm.synced_folder ".", "/vagrant"
    worker.vm.provision "shell", privileged: true, path: "scripts/worker.sh" ,
    env: {
      "MASTER_IP" => MASTER_IP ,
      "WORKER_IP" => WORKER_IP
    }
  end
end
